[package]
name = "Lumy_Integrity"
version = "0.0.1"
edition = "2021"

[target.'cfg(target_os = "macos")'.dependencies]
notify = "5.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
